site_name: Docs for the Bavarian Forest National Park Project

site_url: https://dssgxmunich.github.io/bavarian-forest-visitor-monitoring-dssgx-24/

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - executive-summary.md
  - project-background.md
  - methodology-and-approach.md
  - findings-and-results.md
  - limitations-and-challenges.md
  - references-and-appendix.md
  - api-reference.md