site_name: Docs for the Bavarian Forest National Park Project

site_url: https://dssgxmunich.github.io/bavarian-forest-visitor-monitoring-dssgx-24/

theme:
  name: "material"
  features:
    - navigation.indexes

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - project-factsheet.md
  - Our Approach:
    - approach/index.md
    - approach/data.md
    - approach/prediction-pipeline.md
    - approach/user-frontends.md
  - findings-and-results.md
  - limitations-and-challenges.md
  - open-issues.md
  - api-reference.md
  